// Prisma enums - defined locally since we can't generate Prisma client in this environment
export enum Role {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
  VIEWER = 'VIEWER',
}

export enum PlanType {
  FREE = 'FREE',
  PRO = 'PRO',
  ENTERPRISE = 'ENTERPRISE',
}

export enum PageStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum ComponentType {
  HERO = 'HERO',
  CTA = 'CTA',
  PRICING = 'PRICING',
  FEATURES = 'FEATURES',
  TESTIMONIALS = 'TESTIMONIALS',
  FAQ = 'FAQ',
  FORM = 'FORM',
  NEWSLETTER = 'NEWSLETTER',
  HEADER = 'HEADER',
  FOOTER = 'FOOTER',
  CUSTOM = 'CUSTOM',
}

export enum TestStatus {
  DRAFT = 'DRAFT',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED',
}

export enum EventType {
  PAGE_VIEW = 'PAGE_VIEW',
  CLICK = 'CLICK',
  FORM_SUBMIT = 'FORM_SUBMIT',
  SCROLL = 'SCROLL',
  TIME_ON_PAGE = 'TIME_ON_PAGE',
  CONVERSION = 'CONVERSION',
  CUSTOM = 'CUSTOM',
}

export enum OptimizationType {
  VARIANT_GENERATION = 'VARIANT_GENERATION',
  SEO_OPTIMIZATION = 'SEO_OPTIMIZATION',
  CONTENT_PERSONALIZATION = 'CONTENT_PERSONALIZATION',
  HEADLINE_SUGGESTIONS = 'HEADLINE_SUGGESTIONS',
  CTA_OPTIMIZATION = 'CTA_OPTIMIZATION',
}

export enum PersonalizationAction {
  SWAP_COMPONENT = 'SWAP_COMPONENT',
  CHANGE_TEXT = 'CHANGE_TEXT',
  CHANGE_IMAGE = 'CHANGE_IMAGE',
  REDIRECT = 'REDIRECT',
  SHOW_BANNER = 'SHOW_BANNER',
}

export enum IntegrationType {
  STRIPE = 'STRIPE',
  HUBSPOT = 'HUBSPOT',
  SALESFORCE = 'SALESFORCE',
  MAILCHIMP = 'MAILCHIMP',
  ZAPIER = 'ZAPIER',
  WEBHOOK = 'WEBHOOK',
  GOOGLE_ANALYTICS = 'GOOGLE_ANALYTICS',
  FACEBOOK_PIXEL = 'FACEBOOK_PIXEL',
}

export enum TemplateCategory {
  HERO = 'HERO',
  LANDING_PAGE = 'LANDING_PAGE',
  PRICING = 'PRICING',
  DEMO = 'DEMO',
  FUNNEL = 'FUNNEL',
  WAITLIST = 'WAITLIST',
  COMING_SOON = 'COMING_SOON',
}
